name: Ci-pipeline, Docker image, push to GAR.
on:
  push:
    branches: [ dev-branch-1 ]
    # - '.github/workflows/*yaml'
    paths-ignore:
      - '**.md'
      - 'readme/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
           
  workflow_dispatch:
  
env:
  GAR_INFO: northamerica-northeast2-docker.pkg.dev/thedevproj/tdpartifs  
  WEB_APP_NAME: rs-web
  
jobs:

  build-web:
    name: Building WEB IMAGE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
                        
      - name: Setup GCP Service Account
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
      
      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Setup Docker
        run: |
          gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev
      # Build the Docker image
       
      - name: Build-and-push-to-GAR
        run: |
          export TAG=`cat web/VERSION.txt`
          echo $TAG
          echo "$GAR_INFO"/"$WEB_APP_NAME":"$TAG"
          docker build -t "$GAR_INFO"/"$WEB_APP_NAME":"$TAG" web/
          gcloud info
          docker push "$GAR_INFO"/"$WEB_APP_NAME":"$TAG"
  
  
